### ISSUE TITLE
ClassCastException when loading purpur world config

### ISSUE THREAD

**Issue by Blaackyy** [MultiPaper/MultiPaper#359]
Using dev/1.19.3. 

How to reproduce it:
You need to do a fresh MultiPaper install.

1. Start the master
2. Start the fresh server. 
3. Restart it and you'll have that crash.  

The first time it will start as normal, the issue only appears after a restart when the server tries to load the purpur.yml file.

Crash info to ease the debug and the piece of purpur.yml that triggers the cast issue: [Hastebin](https://hastebin.com/share/ihikotizax.scss)

I'm not familiarized with the codebase but did a quick fix just passing the object to a string, then parsing that string to double.

**Comment by ham1255** [comment]
I think this is upstream problem? since there is no way MultiPaper is changing configs of purpur

**Comment by ham1255** [comment]
also most of crash report isn't there as looking into hastebin link
```yml
purpur.yml piece that makes the file load fail. 

      hoe:
        ...
          minecraft:rooted_dirt:
            condition: always
            drops:
              minecraft:hanging_roots: 1
            into: minecraft:dirt
```
